//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbdonghoEntities : DbContext
    {
        public dbdonghoEntities()
            : base("name=dbdonghoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietMauSac> ChiTietMauSac { get; set; }
        public virtual DbSet<DanhGia> DanhGia { get; set; }
        public virtual DbSet<DanhMuc> DanhMuc { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<HinhAnh> HinhAnh { get; set; }
        public virtual DbSet<LichSuDonHang> LichSuDonHang { get; set; }
        public virtual DbSet<MauSac> MauSac { get; set; }
        public virtual DbSet<QuyenHan> QuyenHan { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
        public virtual DbSet<ThuongHieu> ThuongHieu { get; set; }
    
        public virtual int proc_SuaDanhMuc(Nullable<int> iD_DanhMuc, string tenDanhMuc)
        {
            var iD_DanhMucParameter = iD_DanhMuc.HasValue ?
                new ObjectParameter("ID_DanhMuc", iD_DanhMuc) :
                new ObjectParameter("ID_DanhMuc", typeof(int));
    
            var tenDanhMucParameter = tenDanhMuc != null ?
                new ObjectParameter("TenDanhMuc", tenDanhMuc) :
                new ObjectParameter("TenDanhMuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_SuaDanhMuc", iD_DanhMucParameter, tenDanhMucParameter);
        }
    
        public virtual int proc_SuaMauSac(Nullable<int> iD_MauSac, string tenMauSac)
        {
            var iD_MauSacParameter = iD_MauSac.HasValue ?
                new ObjectParameter("ID_MauSac", iD_MauSac) :
                new ObjectParameter("ID_MauSac", typeof(int));
    
            var tenMauSacParameter = tenMauSac != null ?
                new ObjectParameter("TenMauSac", tenMauSac) :
                new ObjectParameter("TenMauSac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_SuaMauSac", iD_MauSacParameter, tenMauSacParameter);
        }
    
        public virtual int proc_SuaSanPham(Nullable<int> iD_SanPham, string tenSanPham, string matKinh, string dayDongHo, string noiSX, Nullable<decimal> giaBan, string gioiThieuNgan, string baoHanh, string sKU, Nullable<int> iD_ThuongHieu)
        {
            var iD_SanPhamParameter = iD_SanPham.HasValue ?
                new ObjectParameter("ID_SanPham", iD_SanPham) :
                new ObjectParameter("ID_SanPham", typeof(int));
    
            var tenSanPhamParameter = tenSanPham != null ?
                new ObjectParameter("TenSanPham", tenSanPham) :
                new ObjectParameter("TenSanPham", typeof(string));
    
            var matKinhParameter = matKinh != null ?
                new ObjectParameter("MatKinh", matKinh) :
                new ObjectParameter("MatKinh", typeof(string));
    
            var dayDongHoParameter = dayDongHo != null ?
                new ObjectParameter("DayDongHo", dayDongHo) :
                new ObjectParameter("DayDongHo", typeof(string));
    
            var noiSXParameter = noiSX != null ?
                new ObjectParameter("NoiSX", noiSX) :
                new ObjectParameter("NoiSX", typeof(string));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(decimal));
    
            var gioiThieuNganParameter = gioiThieuNgan != null ?
                new ObjectParameter("GioiThieuNgan", gioiThieuNgan) :
                new ObjectParameter("GioiThieuNgan", typeof(string));
    
            var baoHanhParameter = baoHanh != null ?
                new ObjectParameter("BaoHanh", baoHanh) :
                new ObjectParameter("BaoHanh", typeof(string));
    
            var sKUParameter = sKU != null ?
                new ObjectParameter("SKU", sKU) :
                new ObjectParameter("SKU", typeof(string));
    
            var iD_ThuongHieuParameter = iD_ThuongHieu.HasValue ?
                new ObjectParameter("ID_ThuongHieu", iD_ThuongHieu) :
                new ObjectParameter("ID_ThuongHieu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_SuaSanPham", iD_SanPhamParameter, tenSanPhamParameter, matKinhParameter, dayDongHoParameter, noiSXParameter, giaBanParameter, gioiThieuNganParameter, baoHanhParameter, sKUParameter, iD_ThuongHieuParameter);
        }
    
        public virtual int proc_SuaThuongHieu(Nullable<int> iD_ThuongHieu, string tenThuongHieu)
        {
            var iD_ThuongHieuParameter = iD_ThuongHieu.HasValue ?
                new ObjectParameter("ID_ThuongHieu", iD_ThuongHieu) :
                new ObjectParameter("ID_ThuongHieu", typeof(int));
    
            var tenThuongHieuParameter = tenThuongHieu != null ?
                new ObjectParameter("TenThuongHieu", tenThuongHieu) :
                new ObjectParameter("TenThuongHieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_SuaThuongHieu", iD_ThuongHieuParameter, tenThuongHieuParameter);
        }
    
        public virtual int proc_ThemDanhMuc(string tenDanhMuc)
        {
            var tenDanhMucParameter = tenDanhMuc != null ?
                new ObjectParameter("TenDanhMuc", tenDanhMuc) :
                new ObjectParameter("TenDanhMuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ThemDanhMuc", tenDanhMucParameter);
        }
    
        public virtual int proc_ThemMauSac(string mauSac)
        {
            var mauSacParameter = mauSac != null ?
                new ObjectParameter("MauSac", mauSac) :
                new ObjectParameter("MauSac", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ThemMauSac", mauSacParameter);
        }
    
        public virtual int proc_ThemSanPham(string tenSanPham, string matKinh, string dayDongHo, string noiSX, Nullable<decimal> giaBan, string gioiThieuNgan, string baoHanh, string sKU, Nullable<int> iD_ThuongHieu)
        {
            var tenSanPhamParameter = tenSanPham != null ?
                new ObjectParameter("TenSanPham", tenSanPham) :
                new ObjectParameter("TenSanPham", typeof(string));
    
            var matKinhParameter = matKinh != null ?
                new ObjectParameter("MatKinh", matKinh) :
                new ObjectParameter("MatKinh", typeof(string));
    
            var dayDongHoParameter = dayDongHo != null ?
                new ObjectParameter("DayDongHo", dayDongHo) :
                new ObjectParameter("DayDongHo", typeof(string));
    
            var noiSXParameter = noiSX != null ?
                new ObjectParameter("NoiSX", noiSX) :
                new ObjectParameter("NoiSX", typeof(string));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(decimal));
    
            var gioiThieuNganParameter = gioiThieuNgan != null ?
                new ObjectParameter("GioiThieuNgan", gioiThieuNgan) :
                new ObjectParameter("GioiThieuNgan", typeof(string));
    
            var baoHanhParameter = baoHanh != null ?
                new ObjectParameter("BaoHanh", baoHanh) :
                new ObjectParameter("BaoHanh", typeof(string));
    
            var sKUParameter = sKU != null ?
                new ObjectParameter("SKU", sKU) :
                new ObjectParameter("SKU", typeof(string));
    
            var iD_ThuongHieuParameter = iD_ThuongHieu.HasValue ?
                new ObjectParameter("ID_ThuongHieu", iD_ThuongHieu) :
                new ObjectParameter("ID_ThuongHieu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ThemSanPham", tenSanPhamParameter, matKinhParameter, dayDongHoParameter, noiSXParameter, giaBanParameter, gioiThieuNganParameter, baoHanhParameter, sKUParameter, iD_ThuongHieuParameter);
        }
    
        public virtual int proc_ThemThuongHieu(string tenThuongHieu)
        {
            var tenThuongHieuParameter = tenThuongHieu != null ?
                new ObjectParameter("TenThuongHieu", tenThuongHieu) :
                new ObjectParameter("TenThuongHieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ThemThuongHieu", tenThuongHieuParameter);
        }
    
        public virtual ObjectResult<proc_XemDanhMuc_Result> proc_XemDanhMuc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_XemDanhMuc_Result>("proc_XemDanhMuc");
        }
    
        public virtual ObjectResult<proc_XemMauSac_Result> proc_XemMauSac()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_XemMauSac_Result>("proc_XemMauSac");
        }
    
        public virtual ObjectResult<proc_XemSanPham_Result> proc_XemSanPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_XemSanPham_Result>("proc_XemSanPham");
        }
    
        public virtual ObjectResult<proc_XemThuongHieu_Result> proc_XemThuongHieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_XemThuongHieu_Result>("proc_XemThuongHieu");
        }
    
        public virtual int proc_XoaDanhMuc(Nullable<int> iD_DanhMuc)
        {
            var iD_DanhMucParameter = iD_DanhMuc.HasValue ?
                new ObjectParameter("ID_DanhMuc", iD_DanhMuc) :
                new ObjectParameter("ID_DanhMuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_XoaDanhMuc", iD_DanhMucParameter);
        }
    
        public virtual int proc_XoaMauSac(Nullable<int> iD_MauSac)
        {
            var iD_MauSacParameter = iD_MauSac.HasValue ?
                new ObjectParameter("ID_MauSac", iD_MauSac) :
                new ObjectParameter("ID_MauSac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_XoaMauSac", iD_MauSacParameter);
        }
    
        public virtual int proc_XoaSanPham(Nullable<int> iD_SanPham)
        {
            var iD_SanPhamParameter = iD_SanPham.HasValue ?
                new ObjectParameter("ID_SanPham", iD_SanPham) :
                new ObjectParameter("ID_SanPham", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_XoaSanPham", iD_SanPhamParameter);
        }
    
        public virtual int proc_XoaThuongHieu(Nullable<int> iD_ThuongHieu)
        {
            var iD_ThuongHieuParameter = iD_ThuongHieu.HasValue ?
                new ObjectParameter("ID_ThuongHieu", iD_ThuongHieu) :
                new ObjectParameter("ID_ThuongHieu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_XoaThuongHieu", iD_ThuongHieuParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int proc_ThemChiTietDanhMuc(Nullable<int> iD_SanPham, Nullable<int> iD_DanhMuc)
        {
            var iD_SanPhamParameter = iD_SanPham.HasValue ?
                new ObjectParameter("ID_SanPham", iD_SanPham) :
                new ObjectParameter("ID_SanPham", typeof(int));
    
            var iD_DanhMucParameter = iD_DanhMuc.HasValue ?
                new ObjectParameter("ID_DanhMuc", iD_DanhMuc) :
                new ObjectParameter("ID_DanhMuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ThemChiTietDanhMuc", iD_SanPhamParameter, iD_DanhMucParameter);
        }
    }
}
