//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.LichSuDonHang = new HashSet<LichSuDonHang>();
        }
    
        public int ID_DonHang { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string SoDT { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public string DonViVanChuyen { get; set; }
        public Nullable<System.DateTime> NgayGHDuKien { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public string MaVanDon { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> ID_TaiKhoan { get; set; }
        public string GhiChu { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuDonHang> LichSuDonHang { get; set; }
    }
}
